name: todo_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  event_bus_plus: ^0.6.2
  logging_appenders: ^1.3.1
  universal_io: ^2.2.2
  infrastructure:
    path: ../infrastructure
  localizations:
    path: ../localizations


dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
