name: fdd_api
description: "A new Flutter package project."
version: 0.0.1
homepage:  https://fredrott.substack.com

environment:
  sdk: ^3.7.0-209.1.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  result_dart: ^2.0.0
  result_command: ^1.3.0
  equatable: ^2.0.7
  kt_dart: ^1.1.0
  uuid: ^4.5.1
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  freezed: ^2.5.8
  lint: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.


  