name: fdd_api
description: "A new Flutter package project."
version: 0.0.1
homepage:  https://fredrott.substack.com

environment:
  sdk: ^3.7.0-209.1.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  kt_dart: ^1.1.0
  uuid: ^4.5.1
  faker: ^2.2.0
  data_fixture_dart: ^2.2.0
  formz: ^0.8.0
  result_dart: ^2.0.0
  result_command: ^1.3.0
          
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.


  